### ISSUE TITLE
Create A New Reminder

### ISSUE THREAD

**Issue by martensonbj** [turingschool-projects/1608-remember-1#5]
At the bottom of the `reminders.hbs` template, there should be a button that routes the user to `'/new'` where users can create a new reminder.

* The new reminder should have inputs for the title, date, and notes.
* The new reminder should have a button for submitting the new note.
* Pressing the button, should submit reminder to the database and have it shown in the Reminders list.

**Hot Tip**: TDD is really helpful.

**Comment by andrewLcrist** [comment]
@martensonbj @Tman22 @nfosterky @brittanystoroz 

"There should be a button that routes the user" - does this have to actually be a `<button>` or can this be text, styled like a button, used simply to redirect to the `/new` page?

**Comment by andrewLcrist** [comment]
Disregard previous comment.
